### ISSUE TITLE
showing device offline when connecting from LAN

### ISSUE THREAD

**Issue by chunfeng-zhang** [kiddlu/android-adbd-for-linux#1]
It works great when I use ```adb connect 127.0.0.1:5555```.
But when I issue ```adb connect 192.168.56.102:555``` from another host in the same LAN, ```adb devices``` shows the connected device offline.

**Comment by kiddlu** [comment]
> It works great when I use `adb connect 127.0.0.1:5555`.
> But when I issue `adb connect 192.168.56.102:555` from another host in the same LAN, `adb devices` shows the connected device offline.

Really? It works well for me.
You can check your host firewall

**Comment by chunfeng-zhang** [comment]
Thanks for your quick response. I have figured out my problem. 
Before I connected  from another host in LAN, I had made a connection from localhost. Due to the adbd can not be connected by two adb client simultaneously which makes the later connection failed.
